#!/usr/bin/python

BAD_REQUEST_CODE = 400
INTERNAL_SERVER_ERROR_CODE = 500
METHOD_NOT_ALLOWED_CODE = 405
NOT_FOUND_CODE = 404
TIME_OUT_CODE = 408
CONFLICT_ERROR_CODE = 409
UNAUTHORIZED_ERROR_CODE = 401

JSON_CONTENT_TYPE = "application/json"
POST_METHOD = "POST"
GET_METHOD = "GET"
