RPC_ETHEREUM_PORT = 8545
RPC_ETHEREUM_HOST = "ethereumgo"

RPC_ENDPOINT = "http://{}:{}".format(RPC_ETHEREUM_HOST, RPC_ETHEREUM_PORT)

WS_ETHEREUM_PORT = 8546

WS_ENDPOINT = "ws://{}:{}".format(RPC_ETHEREUM_HOST, WS_ETHEREUM_PORT)
