NEW_BLOCK_TOPIC = "newBlock"
ADDRESS_BALANCE_SUBSCRIPTION_TOPIC = "addressBalanceSubscription"
ADDRESS_BALANCE_UNSUBSCRIPTION_TOPIC = "addressBalanceUnSubscription"
CLOSE_CLIENT_CONNECTION_TOPIC = "closeClientConnection"
