import os


RPC_CORE_HOST = "bitcoincore"
RPC_CORE_PORT = 8332
RPC_CORE_USER = "swapper"
RPC_CORE_PASSWORD = "swapper"

RPC_ELECTRUM_HOST = "electrum"
RPC_ELECTRUM_PORT = 30000
RPC_ELECTRUM_USER = "swapper"
RPC_ELECTRUM_PASSWORD = "swapper"

BITCOIN_CALLBACK_PATH = "/bitcoincallback"
BITCOIN_CALLBACK_ENDPOINT = "http://{}:{}{}".format("connector", 80, BITCOIN_CALLBACK_PATH)
ELECTRUM_NAME = "electrum"

RPC_CORE_ENDPOINT = 'http://{}:{}@{}:{}'.format(RPC_CORE_USER, RPC_CORE_PASSWORD, RPC_CORE_HOST, RPC_CORE_PORT)
RPC_ELECTRUM_ENDPOINT = 'http://{}:{}@{}:{}'.format(RPC_ELECTRUM_USER, RPC_ELECTRUM_PASSWORD, RPC_ELECTRUM_HOST, RPC_ELECTRUM_PORT)
