#!/usr/bin/python3
from . import utils

RPC_MONEROD_PORT = 38081
RPC_MONEROD_HOST = "monerod"

RPC_WALLET_PORT = 38088
RPC_WALLET_HOST = "wallet"
RPC_MONEROD_ENDPOINT = "json_rpc"

WALLET_NAME = utils.getWalletName()
WALLET_PASSWORD = "swapper"

RPC_MONEROD_ENDPOINT = "http://{}:{}/{}".format(RPC_MONEROD_HOST, RPC_MONEROD_PORT, RPC_MONEROD_ENDPOINT)
RPC_WALLET_ENDPOINT = "http://{}:{}/{}".format(RPC_WALLET_HOST, RPC_WALLET_PORT, RPC_MONEROD_ENDPOINT)
